/* Generated By:JavaCC: Do not edit this line. FlowDotConstants.java */
package com.chaos.graphviz.flow.jj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FlowDotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_STEP = 6;
  /** RegularExpression Id. */
  int END_STEP = 7;
  /** RegularExpression Id. */
  int IF_STEP = 8;
  /** RegularExpression Id. */
  int STEP = 9;
  /** RegularExpression Id. */
  int TO = 10;
  /** RegularExpression Id. */
  int CALLED = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int COMMENT = 13;
  /** RegularExpression Id. */
  int FLOW_NAME = 14;
  /** RegularExpression Id. */
  int LABEL = 15;
  /** RegularExpression Id. */
  int LINE_END = 16;
  /** RegularExpression Id. */
  int ALPHA = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int CHINESE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"start\"",
    "\"end\"",
    "\"ifstep\"",
    "\"step\"",
    "\"to\"",
    "\"called\"",
    "\"and\"",
    "\"comment\"",
    "<FLOW_NAME>",
    "<LABEL>",
    "\";\"",
    "<ALPHA>",
    "<NUMBER>",
    "<CHINESE>",
  };

}
